<span style="font-size:10pt">AI @ ENSPIMA_2022-2023 / v1.0 september 2022 / Jean-Luc CHARLES (Jean-Luc.charles@ensam.eu) / CC BY-SA 4.0 /</span>

# <img align="middle" src="./img/alarmClock.png" width="60" height="60">  __Wake up your Python__ ! part 2<a name="top"></a>

## [ 1 $-$ Conversion <span style="color:green">list</span> <-> <span style="color:green">numpy.ndarray</span>](#1)
## [ 2 $-$ Reading ASCII files $-$ Encoding](#2)
## [ 3 $-$ Tree manipulation: the `os` module](#3)
## [ 4 $-$ Reading image files](#4)
## [ 5 $-$ Drawing curves with `matplolib`](#5)
## [ 6 $-$ Programming techniques](#6)


<div class="alert alert-block alert-info"> <span style="color:#000080">
For each example in this notebook, take care to read the explanations given and to execute the Python cells with $\left(\mathtt{Shift+Enter}\right)$, before proceeding to the exercises.
</span>
</div>

## __1 $-$ Conversion <span style="color:green">list</span> <-> <span style="color:green">numpy.ndarray</span>__ <a name="1"></a>

Objects of type <span style="color:green">list</span> are very suitable for collecting data, 
but they cannot be used for doing **advanced calculations**.<br>
=> You **must** know how to convert <span style="color:green">list</span> objects into arrays
<span style="color:green">numpy.ndarray</span> and vice versa:<br>

`M = numpy.array(L)` converts the  <span style="color:green">list</span> `L`  to the <span style="color:green">ndarray</span> (n-dimensional array) `M` 
(see the [array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) function of **numpy**)<br>

`L = M.tolist()` converts the <span style="color:green">ndarray</span> `M` to the <span style="color:green">list</span> `L` 
(see method [numpy.ndarray.tolist](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html)).

<div class="alert alert-block alert-info">
<span style="color: #0000BB;font-weight: bold; font-size:large;">Exercise 1.1 $–$ Conversions list ↔ vector</span>
<div><span style="color: #0000BB">
    
- Define the list comprehension `L1` of the squares of the integers from 1 to 9.<b>

- Define and display `v1`, the conversion of `L1` to a <span style="color:green">numpy.ndarray</span>.<br>

- Display the type of `v1` and its attributes
<span style="color:green">dtype</span>,
<span style="color:green">shape</span>,
<span style="color:green">ndim</span>,
<span style="color:green">size</span>,
<span style="color:green">itemsize</span> and
<span style="color:green">nbytes</span>.
    
- Define and display `v2`, the conversion of `L1` to a
<span style="color:green">ndarray</span> of integers, obtained by passing the additional argument
<span style="color:brown">dtype=</span><span style="color:green">"uint8"</span>
to the `array` function.<br>
Display `V2.itemsize`.<br>

- Define **without an explicit loop** the vector `v3`, such that for all $i$:
$v3[i]\,=\,\sqrt{v2[i]}\,\cos(v2[i]\,\pi/20)$.<br>
$\leadsto$ tips: use `np.sqrt(...)`, `np.cos(...)` and `np.pi`.<br>
Show `v3` and its attributes
<span style="color:green">shape</span>,
<span style="color:green">ndim</span> and
<span style="color:green">size</span>.

- Modify `v3` with the instruction `v3.shape = (3,3)`: display again `v3` and its attributes
<span style="color:green">shape</span>,
<span style="color:green">ndim</span> and
<span style="color:green">size</span>; observe what has changed.

- Convert `v3` to the `L3` list using the`tolist` method of the class <span style="color:green">ndarray</span>. Display `L3`.
</span></div>

In [2]:
L1 = [n**2 for n in range(1,10)] ; L1

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [6]:
import numpy as np
v1 = np.array(L1) ; v1

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
type(v1)

numpy.ndarray

In [30]:
print('v1.dtype:', v1.dtype)
print('v1.shape:', v1.shape)
print('v1.ndim:', v1.ndim)
print('v1.size:', v1.size)
print('v1.itemsize:', v1.itemsize)
print('v1.nbytes:', v1.nbytes)

v1.dtype: int64
v1.shape: (9,)
v1.ndim: 1
v1.size: 9
v1.itemsize: 8
v1.nbytes: 72


In [31]:
v2 = np.array(L1, dtype="uint8") 
print(v2)
print(v2.itemsize)

[ 1  4  9 16 25 36 49 64 81]
1


In [33]:
v3 = np.sqrt(v2)*np.cos(v2*np.pi/20)
v3

array([ 0.98768834,  1.61803399,  0.4693034 , -3.23606798, -3.53553391,
        4.85410197,  1.09504126, -6.47213595,  8.88919507])

In [34]:
print('v3.shape:', v1.shape)
print('v3.ndim:', v1.ndim)
print('v3.size:', v1.size)

v3.shape: (9,)
v3.ndim: 1
v3.size: 9


In [35]:
v3.shape = (3,3)
v3

array([[ 0.98768834,  1.61803399,  0.4693034 ],
       [-3.23606798, -3.53553391,  4.85410197],
       [ 1.09504126, -6.47213595,  8.88919507]])

In [36]:
print('v3.shape:', v1.shape)
print('v3.ndim:', v1.ndim)
print('v3.size:', v1.size)

v3.shape: (9,)
v3.ndim: 1
v3.size: 9


In [37]:
L3 = v3.tolist()
L3

[[0.9876883405951377, 1.6180339887498951, 0.46930339512069275],
 [-3.23606797749979, -3.5355339059327386, 4.854101966249684],
 [1.0950412552816244, -6.472135954999582, 8.88919506535624]]

[top](#top)

<div class="alert alert-block alert-info">
<span style="color: #0000BB;font-weight: bold; font-size:large;">Exercise 1.2 $–$ Conversion list <-> matrix</span>
<span style="color: #0000BB">
  
- Observe the result of the two cells below:
</span></div>

In [24]:
[10*i+j for i in range(1,4) for j in range(1,4)]

[11, 12, 13, 21, 22, 23, 31, 32, 33]

In [25]:
[[10*i+j for j in range(1,4)] for i in range(1,4)]

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

<div class="alert alert-block alert-info">
<span style="color: #0000BB">
    
- Deduce two different ways to define the matrix `M` of general term $M_{i,\,j}=j^{\,i}$ with $(i,j) \in [1;5]\times [1;5]$ using list comprehensions defined then converted to <span style="color:green">ndarray</span> .
</span></div>

In [26]:
import numpy as np
L = [j**i for i in range(1,6) for j in range(1,6)]
V = np.array(L); V

array([   1,    2,    3,    4,    5,    1,    4,    9,   16,   25,    1,
          8,   27,   64,  125,    1,   16,   81,  256,  625,    1,   32,
        243, 1024, 3125])

In [27]:
V.shape = (5,5); V

array([[   1,    2,    3,    4,    5],
       [   1,    4,    9,   16,   25],
       [   1,    8,   27,   64,  125],
       [   1,   16,   81,  256,  625],
       [   1,   32,  243, 1024, 3125]])

In [28]:
L = [[j**i for j in range(1,6)] for i in range(1,6)]; L

[[1, 2, 3, 4, 5],
 [1, 4, 9, 16, 25],
 [1, 8, 27, 64, 125],
 [1, 16, 81, 256, 625],
 [1, 32, 243, 1024, 3125]]

In [29]:
M = np.array(L); M

array([[   1,    2,    3,    4,    5],
       [   1,    4,    9,   16,   25],
       [   1,    8,   27,   64,  125],
       [   1,   16,   81,  256,  625],
       [   1,   32,  243, 1024, 3125]])

[top](#top)

## __2 $-$ Reading ASCII files $-$ Encoding__ <a name="2"></a>

ASCII files are read with the <span style="color:green">open</span> primitive which returns an iterable object of type </span><span style="color:green">TextIOWrapper</span>: <br />
    **<span style="font-family:courier">
<span style="color:#B08000">with</span> <span style="color:#800080">open</span>( <span style="color:#808080">< file path ></span>, <span style="color:#008000">"r"</span>, encoding=<span style="color:#808080">< encoding_specification ></span>)<span style ="color:#B08000"> as</span> F:<br>
    $\phantom{---}$...</p> </span>**
    
Reading accented characters requires specifying their **encoding** for correct interpretation. The most common encodings are **utf8** (Mac OS X, GNU/Linux default encoding) and **cp1252** or **iso8859-15** (Windows default encoding).<br />

Using a **<span style="font-family:courier;color:#B08000">with</span>** block automatically closes the file as soon as you exit the block.

<div class="alert alert-block alert-info">
<span style="color: #0000BB;font-weight: bold; font-size:large;">Exercise 2.1 –Reading of an ASCII file, decoding accented characters</span>
<span style="color: #0000BB">
  
- Read the `./data/accents.txt` file in a string with the primitive <span style="color:green">read</span>, specifying **cp1252** as encoding, then display the resulting string.
- Same work, this time specifying **utf8** as the encoding.
</span></div>

In [43]:
with open("data/accents.txt", "r", encoding="cp1252") as F :
    s = F.read()
print(s)

La présence de caractères accentués dans un fichier
ASCII peut poser des problèmes pour la restitution 
graphique des caractères.



In [44]:
with open("data/accents.txt", "r", encoding="utf8") as F :
    s = F.read()
print(s)

La présence de caractères accentués dans un fichier
ASCII peut poser des problèmes pour la restitution 
graphique des caractères.



[top](#top)

<div class="alert alert-block alert-info">
<span style="color: #0000BB;font-weight: bold; font-size:large;">Exercise 2.2 $–$ Get the list of the lines of an ASCII file</span>
<span style="color: #0000BB">
  
- Define `L`, the list of the lines of the file `data/data.txt` by using the primitive <span style="color:green">readlines</span>. Display `L`.

- Now define `L` in order to eliminate lines that are comments (starting with `#`). Display `L`.
</span></div>

In [45]:
with open("data/data.txt", "r", encoding="utf8") as F :
    L = F.readlines()
print(L)

['# Time [s]\tStress [Pa]\tStrain\n', '0.000000e+00\t3.320000e+05\t4.340000e-05\n', '1.700000e-01\t6.010000e+06\t3.290000e-04\n', '3.400000e-01\t1.150000e+07\t9.710000e-04\n', '5.100000e-01\t1.710000e+07\t1.320000e-03\n', '6.800000e-01\t2.260000e+07\t1.850000e-03\n', '8.500000e-01\t2.870000e+07\t2.220000e-03\n', '1.020000e+00\t3.150000e+07\t2.620000e-03\n', '1.190000e+00\t3.260000e+07\t3.040000e-03\n', '1.360000e+00\t3.170000e+07\t3.460000e-03\n', '1.530000e+00\t3.330000e+07\t4.020000e-03\n', '1.700000e+00\t3.270000e+07\t4.270000e-03\n', '1.870000e+00\t3.270000e+07\t4.910000e-03\n', '2.040000e+00\t3.440000e+07\t5.250000e-03\n', '2.210000e+00\t3.460000e+07\t5.660000e-03\n', '# Création : Jeudi 3 novembre 2011, 23:09:24\n']


In [48]:
# Variante :
L = [line for line in L if line[0] != "#" ]
print(L)

['0.000000e+00\t3.320000e+05\t4.340000e-05\n', '1.700000e-01\t6.010000e+06\t3.290000e-04\n', '3.400000e-01\t1.150000e+07\t9.710000e-04\n', '5.100000e-01\t1.710000e+07\t1.320000e-03\n', '6.800000e-01\t2.260000e+07\t1.850000e-03\n', '8.500000e-01\t2.870000e+07\t2.220000e-03\n', '1.020000e+00\t3.150000e+07\t2.620000e-03\n', '1.190000e+00\t3.260000e+07\t3.040000e-03\n', '1.360000e+00\t3.170000e+07\t3.460000e-03\n', '1.530000e+00\t3.330000e+07\t4.020000e-03\n', '1.700000e+00\t3.270000e+07\t4.270000e-03\n', '1.870000e+00\t3.270000e+07\t4.910000e-03\n', '2.040000e+00\t3.440000e+07\t5.250000e-03\n', '2.210000e+00\t3.460000e+07\t5.660000e-03\n']


[top](#top)

## __3 $-$ Tree manipulation: the `os` module__ <a name="3"></a>

The `os` and `os.path` modules contain many functions dedicated to manipulating files and
directories (also called folders). In the table below `<path>` is a string
giving the (relative or absolute) path of a file or directory:<br />

<img src="Images/module-os.png" style="height:230px;width:700px" align="left"/>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
Helpful Notes:
- the <span style="color:green">"/"</span> character can be used as a directory name separator for any operating system,
- the current directory can be designated by the shortcut <span style="color:green">"."</span>, the parent directory by the shortcut <span style="color:green">".."</ span>.

[top](#top)

## __4 $-$ Reading image files__ <a name="4"></a>

The `os` and `os.path` modules contain many functions dedicated to manipulating files and
directories (also called folders). In the table below `<path>` is a string
giving the (relative or absolute) path of a file or directory:<br />

<img src="Images/module-os.png" style="height:230px;width:700px" align="left"/>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
Helpful Notes:
- the <span style="color:green">"/"</span> character can be used as a directory name separator for any operating system,
- the current directory can be designated by the shortcut <span style="color:green">"."</span>, the parent directory by the shortcut <span style="color:green">".."</ span>.

[top](#top)

## __5 $-$ Drawing curves with `matplolib`__ <a name="5"></a>

The **matplotlib.pyplot** module allows you to plot 2D, 3D and other curves.... see the gallery on the site [matplotlib.org/gallery.html](https://matplotlib.org/ gallery.html).

**Tutorials**:<br>
- on the matplotlib site: https://matplotlib.org/stable/ <br />
- at the LABRI laboratory: http://www.labri.fr/perso/nrougier/teaching/matplotlib/ <br>

[top](#top)

## __6 $-$ Programming techniques__ <a name="5"></a>

Among the many programming techniques taught in software engineering, two techniques must be
understood and used within the framework of the *Mathematics and computer science* teaching unit:
- the management of **exceptions**, with the keywords <span style="color:green;font-weight:bold">try</span> and
<span style="color:green;font-weight:bold">except</span>,
- integration of **unit tests** in Python files and how to exclude them from the <span style="color:green;font-weight:bold">import</span> mechanism.

### 6.1 $-$ Try/except block

The principle is to write (in order):
- a <span style="color:green;font-weight:bold">try</span> block that contains Python instructions
likely to fail and therefore *throw* **exceptions** (normally resulting in <span style="color:red">error messages in red</span> on the screen...)
- a <span style="color:green;font-weight:bold">except</span> block, responsible for *catching* these exceptions (if they occur) and doing appropriate processing, which can be summarized to a simple display of a message (print), followed by a *proper* exit or continuation of the program.
```Python
#...
try:
    # try block
    # ...
except:
    # block to handle exceptions
    #...
```

###  6.2 $-$ Tests unitaires (concerne l'écriture des fichiers .py)
Le problème des tests unitaires intégrés dans un fichier Python importé comme un module est que ces
tests sont exécutés (comme le reste du programme) par la primitive 
<span style="color:green;font-weight:bold">import</span> : ceci n’est pas forcément le
comportement recherché lorsqu’on utilise un fichier Python comme un module ! <br /><br />
La solution consiste à exclure les tests unitaires de l’exécution grâce à un *bloc if* portant sur la valeur
de l’objet prédéfini <span style="color:brown">\_\_name\_\_</span> :

**Exemple** avec le fichier <tt><b><span style="color:blue">test.py</span></b></tt> contenant le code : 
```Python
print("__name__ :", __name__)
```
L’exécution de <tt><b><span style="color:blue">test.py</span></b></tt> dans le shell Python affiche :<br />
`__name__ : __main__`<br />
car dans le contexte de l’exécution directe par un shell Python, `__name__` vaut 
<span style="color:brown"> "\_\_main\_\_" </span>.

L’exécution indirecte par <span style="color:green;font-weight:bold">import</span> du module **test** (correspondant au fichier <tt><b><span style="color:blue">test.py</span></b></tt>) dans le shell Python :
```Python
>>> import test
__name__ : __test__ 
```
car dans le contexte de l’exécution d’un module par la primitive 
<span style="color:green;font-weight:bold">import</span>,
`__name__` vaut le nom du module.